name: PRs Merged Checker

on:
  pull_request:
    types: [closed]
    branches:
      - develop1
      - develop2

jobs:
  echo_jobs_start:
    runs-on: self-hosted
    steps:
      - run: echo "jobs started!!"
  check-prs-merged:
    runs-on: self-hosted
    steps:
      - name: Check if PR is merged
        if: github.event.pull_request.merged == true
        run: |
          echo "PR to ${GITHUB_REF##*/} merged."
      - name: Set merged flag
        if: github.event.pull_request.merged == true
        run: |
          echo "${GITHUB_REF##*/}" > merged_branch.txt
      - name: Upload merged branch artifact
        if: github.event.pull_request.merged == true
        uses: actions/upload-artifact@v3
        with:
          name: merged-branch
          path: merged_branch.txt

  trigger-docker-build:
    needs: check-prs-merged
    runs-on: self-hosted
    steps:
      - name: Download merged branch artifacts
        uses: actions/download-artifact@v3
        with:
          name: merged-branch
          path: ./artifacts
      - name: Check both branches merged
        id: check
        run: |
          git fetch origin develop1 develop2
          # Check if both develop1 and develop2 have been merged into main
          if git merge-base --is-ancestor origin/develop1 origin/main && \
             git merge-base --is-ancestor origin/develop2 origin/main; then
            echo "both_merged=true" >> $GITHUB_OUTPUT
          else
            echo "both_merged=false" >> $GITHUB_OUTPUT
          fi
      - name: Trigger Docker Build and Push workflow
        if: steps.check.outputs.both_merged == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-build-push.yml

# このワークフローは develop1 または develop2 の PR がマージされたときに発火します。
# develop1 と develop2 の両方が main にマージされているかをチェックし、条件を満たせば docker-build-push.yml をトリガーします。
