name: PRs Merged Checker

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  echo_jobs_start:
    runs-on: self-hosted
    steps:
      - run: echo "jobs have been started!"
  check-prs-merged:
    runs-on: self-hosted
    steps:
      - name: Check if PR is merged from develop1 or develop2
        if: github.event.pull_request.merged == true && (github.event.pull_request.head.ref == 'develop1' || github.event.pull_request.head.ref == 'develop2')
        run: |
          echo "PR from ${GITHUB_HEAD_REF} merged to main."
      - name: Set merged flag
        if: github.event.pull_request.merged == true && (github.event.pull_request.head.ref == 'develop1' || github.event.pull_request.head.ref == 'develop2')
        run: |
          echo "${GITHUB_HEAD_REF}" > merged_branch.txt
      - name: Upload merged branch artifact
        if: github.event.pull_request.merged == true && (github.event.pull_request.head.ref == 'develop1' || github.event.pull_request.head.ref == 'develop2')
        uses: actions/upload-artifact@v3
        with:
          name: merged-branch
          path: merged_branch.txt

  trigger-docker-build:
    needs: check-prs-merged
    runs-on: self-hosted
    steps:
      - name: Download merged branch artifacts
        uses: actions/download-artifact@v3
        with:
          name: merged-branch
          path: ./artifacts
      - name: Check both branches merged
        id: check
        run: |
          git fetch origin develop1 develop2 main
          # Check if both develop1 and develop2 have been merged into main
          if git merge-base --is-ancestor origin/develop1 origin/main && \
             git merge-base --is-ancestor origin/develop2 origin/main; then
            echo "both_merged=true" >> $GITHUB_OUTPUT
          else
            echo "both_merged=false" >> $GITHUB_OUTPUT
          fi
      - name: Trigger Docker Build and Push workflow
        if: steps.check.outputs.both_merged == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-build-push.yml

# このワークフローは main ブランチへの PR がマージされたときに発火します。
# develop1 または develop2 から main へのマージを検出し、
# 両方のブランチがマージされている場合に docker-build-push.yml をトリガーします。
